// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnections(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.ConnectionDTO>>;

export function GetHistory(arg1:string):Promise<Array<main.PingSampleDTO>>;

export function GetInitialState():Promise<main.InitialStateDTO>;

export function GetStatus():Promise<main.StatusDTO>;

export function IsPaused():Promise<boolean>;

export function Pause():Promise<boolean>;

export function Refresh():Promise<Array<main.ConnectionDTO>>;

export function Resume():Promise<boolean>;
