// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnections(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConnections'](arg1, arg2, arg3);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}
